import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Primera migración: tablas `roles` y `users` (ver ADR-006).
 *
 * - `roles`: catálogo con PK smallint. Se siembran los cuatro roles base.
 * - `users`: PK uuid (gen_random_uuid), email único, soft delete
 *   (`deleted_at`), FK a `roles`. `password_hash` porque NestJS es dueño del
 *   auth (ADR-010).
 *
 * Nada más en esta migración: menú, pedidos, notificaciones, etc. llegan
 * en migraciones posteriores.
 */
export class InitRolesAndUsers1752537600000 implements MigrationInterface {
  name = 'InitRolesAndUsers1752537600000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // gen_random_uuid() es core desde PG13, pero pgcrypto lo garantiza.
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto";`);

    await queryRunner.query(`
      CREATE TABLE "roles" (
        "id"   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" VARCHAR(50) NOT NULL,
        CONSTRAINT "UQ_roles_name" UNIQUE ("name")
      );
    `);

    await queryRunner.query(`
      CREATE TABLE "users" (
        "id"              UUID NOT NULL DEFAULT gen_random_uuid(),
        "role_id"         SMALLINT NOT NULL,
        "full_name"       VARCHAR(150) NOT NULL,
        "email"           VARCHAR(255) NOT NULL,
        "phone"           VARCHAR(30),
        "whatsapp_number" VARCHAR(30),
        "password_hash"   VARCHAR(255) NOT NULL,
        "is_active"       BOOLEAN NOT NULL DEFAULT true,
        "created_at"      TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at"      TIMESTAMPTZ NOT NULL DEFAULT now(),
        "deleted_at"      TIMESTAMPTZ,
        CONSTRAINT "PK_users_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_users_role" FOREIGN KEY ("role_id")
          REFERENCES "roles" ("id") ON DELETE RESTRICT
      );
    `);

    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_users_email" ON "users" ("email");`,
    );

    // Roles base sembrados como datos (ADR-006): agregar uno nuevo es un INSERT.
    await queryRunner.query(`
      INSERT INTO "roles" ("name") VALUES
        ('customer'),
        ('staff'),
        ('admin'),
        ('superadmin');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "UQ_users_email";`);
    await queryRunner.query(`DROP TABLE IF EXISTS "users";`);
    await queryRunner.query(`DROP TABLE IF EXISTS "roles";`);
  }
}
